// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkZTAu9zSf3AH2gVsnO5DYTmNEXLicMpo',
    appId: '1:645024717879:web:ea9323a4f5de644c7a33b2',
    messagingSenderId: '645024717879',
    projectId: 'cis2203-final-project',
    authDomain: 'cis2203-final-project.firebaseapp.com',
    storageBucket: 'cis2203-final-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMf-IQyG0v2PLw-UeZtXnfxreIXt1b0_M',
    appId: '1:645024717879:android:4b722fe4ce62a16d7a33b2',
    messagingSenderId: '645024717879',
    projectId: 'cis2203-final-project',
    storageBucket: 'cis2203-final-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcN7ewug0WTJ48OPO8fJu3gXTXEbct1Ek',
    appId: '1:645024717879:ios:eaf2e1ea794cfca77a33b2',
    messagingSenderId: '645024717879',
    projectId: 'cis2203-final-project',
    storageBucket: 'cis2203-final-project.appspot.com',
    iosBundleId: 'com.example.mealapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcN7ewug0WTJ48OPO8fJu3gXTXEbct1Ek',
    appId: '1:645024717879:ios:e25efec6fca989af7a33b2',
    messagingSenderId: '645024717879',
    projectId: 'cis2203-final-project',
    storageBucket: 'cis2203-final-project.appspot.com',
    iosBundleId: 'com.example.mealapp.RunnerTests',
  );
}
